name: Ubuntu Build

on:
  push:
    branches: [ "list" ]
  pull_request:
    branches: [ "list" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install libgimp2.0-dev gettext autoconf automake intltool libtool
    - name: configure
      run: |
        ./autogen.sh
        ./configure
    - name: make
      run: |
        make
    - name: make install
      run: sudo make install
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: /usr/local/share/gimp-apng/
        name: ubuntu
      
