name: Ubuntu Build

on:
  push:
    branches: [ "list" ]
  pull_request:
    branches: [ "list" ]

jobs:
  build:

    runs-on: ubuntu-14.04

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install gettext autoconf2.69 automake1.9
    - name: configure
      run: |
        mkdir config
        libtoolize --force --verbose
        aclocal --verbose
        autoheader-2.69 -v
        automake --force-missing --add-missing
        autoconf-2.69 -v
        ./configure
    - name: make
      run: |
        make
    - name: make install
      run: make install
