name: Ubuntu Build

on:
  push:
    branches: [ "list" ]
  pull_request:
    branches: [ "list" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install gettext autoconf automake
    - name: configure
      run: |
        ./autogen.sh
    - name: make
      run: |
        make
    - name: make install
      run: make install
