name: Ubuntu Build

on:
  push:
    branches: [ "list" ]
  pull_request:
    branches: [ "list" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install autoconf2.69
    - name: configure
      run: |
        libtoolize --force
        aclocal
        autoheader-2.69
        automake --force-missing --add-missing
        autoconf-2.69
        ./configure
    - name: make
      run: |
        make
    - name: make install
      run: make install
