name: Windows Build

on:
  push:
    branches: [ "list" ]
  pull_request:
    branches: [ "list" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Cygwin Action
      uses: cygwin/cygwin-install-action@v2
      with:
        packages: autoconf2.5 automake libtool make gcc-g++
    - name: configure
      run: |
        mkdir config
        libtoolize --force
        aclocal
        autoheader-2.69
        automake --force-missing --add-missing
        autoconf-2.69
        bash ./configure
    - name: make
      run: |
        make
    - name: make install
      run: make install
