name: Windows Build

on:
  push:
    branches: [ "list" ]
  pull_request:
    branches: [ "list" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Install Cygwin Action
      uses: cygwin/cygwin-install-action@v2
      with:
        packages: autoconf2.5 automake1.9 automake-wrapper libtool intltool make gcc-g++ pkg-config
        
    - name: configure
      run: |
        mkdir config
        aclocal-1.9 -I config
        autoheader-2.69 -W all
        automake-1.9 -W all --add-missing
        autoconf-2.69 -W all
        intltoolize --automake
        bash ./configure

    - name: make
      run: |
        make
    - name: make install
      run: make install
