name: Windows Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Install Cygwin Action
      uses: cygwin/cygwin-install-action@master
      with:
        packages: autoconf2.5 automake automake-wrapper libtool intltool make gcc-g++ pkg-config
        
    - name: Create config folder
      run: mkdir -p config
  
    - name: Autoconf
      run: |
        C:\cygwin\bin\bash.exe ./autogen.sh
        ls

    - name: make
      run: make
