name: Windows Build

on:
  push:
    branches: [ "list" ]
  pull_request:
    branches: [ "list" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Cygwin Action
      uses: cygwin/cygwin-install-action@v2
      with:
        packages: autoconf2.5 automake1.9 libtool make gcc-g++ pkg-config
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: configure
      run: |
        mkdir config
        ls
        libtoolize --force --verbose
        aclocal-1.9 --verbose
        autoheader-2.69 -v
        automake-1.9 --force-missing --add-missing
        autoconf-2.69 -v
        bash ./configure

    - name: make
      run: |
        make
    - name: make install
      run: make install
