name: Windows Build

on:
  push:
    branches: [ "list" ]
  pull_request:
    branches: [ "list" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Cygwin Action
      uses: cygwin/cygwin-install-action@v2
      with:
        packages: autoconf2.5 automake1.9 libtool make gcc-g++ pkg-config
        
    - name: Set line endings
      run: |
        git config --global core.autocrlf true
        
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: configure
      run: |
        bash ./autogen.sh

    - name: make
      run: |
        make
    - name: make install
      run: make install
